monitor_presence_job:
  cron: "2-59/5 8-17 * * 1-5 America/Denver"
  class: "PresenceMonitoringJob"
  queue: default

process_presence_data_job:
  cron: "0 19 * * 1-5 America/Denver"
  class: "ProcessPresenceDataJob"
  queue: default