monitor_presence_job:
  cron: "2-59/5 8-17 * * 1-5"
  class: "PresenceMonitoringJob"
  queue: default
  timezone: "America/Denver"

process_presence_data_job:
  cron: "0 19 * * 1-5"
  class: "ProcessPresenceDataJob"
  queue: default
  timezone: "America/Denver"