@inning = Inning.create!(name: "2108")
@turing_module = @inning.turing_modules.create!(program: 'Combined', module_number: 4, google_spreadsheet_id: '1v3C4DXVmmvV1r7vEuo0Xo58AwAJ-SligrplOiLUjWnw')
@turing_module = @inning.turing_modules.create!(program: 'FE', module_number: 1,google_spreadsheet_id: '10MNyOoYB4w9QCj9y_90DHVUe8DX2OO8ZoGUm8_4suf4', google_sheet_name: "2105")
@turing_module = @inning.turing_modules.create!(program: 'FE', module_number: 2,google_spreadsheet_id: '10MNyOoYB4w9QCj9y_90DHVUe8DX2OO8ZoGUm8_4suf4', google_sheet_name: "2107")
@turing_module = @inning.turing_modules.create!(program: 'FE', module_number: 3,google_spreadsheet_id: '10MNyOoYB4w9QCj9y_90DHVUe8DX2OO8ZoGUm8_4suf4', google_sheet_name: "2108")
@turing_module = @inning.turing_modules.create!(program: 'BE', module_number: 1,google_spreadsheet_id: '13jZKWzDx87Epgf_DBOy2k2ilFlJXfJU3MdQ8tqv9HaM', google_sheet_name: "2105")
@turing_module = @inning.turing_modules.create!(program: 'BE', module_number: 2,google_spreadsheet_id: '13jZKWzDx87Epgf_DBOy2k2ilFlJXfJU3MdQ8tqv9HaM', google_sheet_name: "2107")
@turing_module = @inning.turing_modules.create!(program: 'BE', module_number: 3,google_spreadsheet_id: '13jZKWzDx87Epgf_DBOy2k2ilFlJXfJU3MdQ8tqv9HaM', google_sheet_name: "2108")
